### ISSUE TITLE
UIList and PropertyGroups/Properties query

### ISSUE THREAD

**Issue by p2or** [torrinworx/Blender_UList#1]
_This is a reply to "UIList and PropertyGroups/Properties query" - the original issue has been opened [here](https://github.com/p2or/blender-loom/issues)_.

> I've been working on an open source Blender add-on for the past 7 months and have been stuck on something for a while now. I haven't been able to figure out a way to use Properties with UILists ...

Hi @torrinworx,

I fully understand that it is complicated to grasp all the details at the beginning. There are a lot of things you can do, but there are also a lot of limitations you have to deal with. For this reason, a mockup or sketch would really help here since [your description is a bit vague](https://github.com/p2or/blender-loom/issues/29) and also hard to guess what your actual goal is based on _"UIList with Property functionality"_.

Anyway, based on your slightly modifed version of my code _I assume_ your goal is to have custom properties per item displayed in one row and access each group right? If so, **your data structure is wrong** and I would not recommend to play with `custom_index` because the property keeps track of the selection. I recommend take your time and [study the code](https://gist.github.com/p2or/d6dfd47366b2f14816f57d2067dcb6a9) I have provided and you'll see that all you'd have to do is adding the properties to `CUSTOM_objectCollection` class which is registered as `CollectionProperty` rather than a `PointerProperty` since you'd have to pass a _collection of items_ to `template_list()`. Should be pretty straight forward to adapt my demo and add the properties you want:

### Data structure `CUSTOM_objectCollection`

```python
...

# -------------------------------------------------------------------
#   Collection
# -------------------------------------------------------------------

class CUSTOM_objectCollection(PropertyGroup):
    #name: StringProperty() -> Instantiated by default
-   obj_type: StringProperty()
-   obj_id: IntProperty()
+   my_bool: BoolProperty()
+   my_string: StringProperty()
+   my_enum: EnumProperty(items=[("R", "r", ""), ("G", "g", ""), ("B", "b", "")]) # EnumProperty has to be imported!
+   my_string2: StringProperty()
    ...

```

### Adding a new item `CUSTOM_OT_actions`

```python
...
if self.action == 'ADD':
    if context.object:
        item = scn.custom.add()
        item.name = context.object.name # can also be a generated string
        scn.custom_index = len(scn.custom)-1
        info = '"%s" added to list' % (item.name)
        self.report({'INFO'}, info)
    else:
        self.report({'INFO'}, "Nothing selected in the Viewport")
return {"FINISHED"}
```

### Drawing of the properties `CUSTOM_UL_items`

```python

# -------------------------------------------------------------------
#   Drawing
# -------------------------------------------------------------------

class CUSTOM_UL_items(UIList):
    def draw_item(self, context, layout, data, item, icon, active_data, active_propname, index):
        split = layout.split(factor=0.2)
        split.label(text="Index: %d" % (index))
        row = split.row()
        row.label(text=item.name) # avoids renaming the item by accident
        row.prop(item, "my_bool", text="")
        row.prop(item, "my_string", text="")
        row.prop(item, "my_enum", text="")

        ...
```
### Accessing the items `CUSTOM_OT_printItems`

```python
- print ("Name:", item.name,"-", item.obj_type, item.obj_id)
+ print ("Name:", item.name,"-", item.my_bool, item.my_string, item.my_enum)
```

----

### Result

<img width="454" alt="Screenshot 2022-04-16 at 15 33 15" src="https://user-images.githubusercontent.com/512368/163676920-a8f1d874-87d0-47f8-b9bd-2778bf36f680.png">

**Console Output** `CUSTOM_OT_printItems`

```python
Name: Cube - False  R
Name: Cube - True Bla B
Name: Cube - False Blub R
```

_Once your custom data is registered, I recommend use the python console to test:_

```python
>>> item = C.scene.custom.add() # add another item
>>> item.name = "Bla" # give it a name
>>> item.my_enum = "B" # set the enum to "B"
```

_You can also print the data using the console to verify whether all is working:_

```python
>>> C.scene.custom_index
1

>>> C.scene.custom.items()
[('Cube', bpy.data.scenes['Scene'].custom[0]), 
 ('Cube', bpy.data.scenes['Scene'].custom[1]), 
 ('Cube', bpy.data.scenes['Scene'].custom[2])]

>>> C.scene.custom[C.scene.custom_index]
bpy.data.scenes['Scene'].custom[1]

>>> selected_item = C.scene.custom[C.scene.custom_index]
>>> selected_item.my_bool
True

```

**Does that help?** If not, please provide more details, the link to the add-on, a mockup or sketch as mentioned. 

>  I'd really appreciate it if you can help me out with this, I'm also willing to compensate you for your time as solving this matter is very important to me and I value your input.

Not a native speaker, so I need a lot of time documenting add-ons like [Loom](https://github.com/p2or/blender-loom) and I would appreciate any help on that.

Cheers,
Christian

**Comment by torrinworx** [comment]
Oh wow thank you so much @p2or!! This is incredibly helpful, I really appreciate you taking the time to answer my question.

This makes so much sense now, thank you for the detailed answer. I managed to get a working adaptation of this example to work: https://github.com/torrinworx/Blend_My_NFTs/blob/UIList_Implementation/main/UILists.py

I'll take a look at Loom and your other add-ons and see where I can contribute, I'll do the best I can however I must say I'm not the greatest at Blender 😅
